ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Overview
This project showcases some of the tips pointed out in https://youtu.be/mqoU2C-USP0?si=9_9_0yrDdI838sPi[The C4 Model – Misconceptions, Misuses & Mistakes], focusing on an enterprise view of the systems. I'm especially curious as how to model microservices written by different teams. Simon presents the following guidelines for handling systems written by different teams:

* model each microservice as a Software System
* if you don't own a system, don't model its details, just the connections
* let each team fill in the details
* use include expressions to only show afferent and efferent couplings to manage diagram complexity -- focus on what is useful
* do that for each service's container diagram
* the trade-off is that you miss the big picture
* use the graph to get the big picture
* can export the model into other tools, https://www.ilograph.com/[Ilograph] for example
* only show containers within the software system within the scope of the diagram
* external services can be modeled as software systems with just references
* don't show internals (containers) of external systems we don't own or are not in context

== Implementation
Structurizr supports only a single workspace at a time, encouraging us to launch different views depending on the audience.  We'll make use of  https://docs.structurizr.com/dsl/cookbook/workspace-extension/[Workspace extension] and the ideas expressed in https://docs.structurizr.com/usage/enterprise[Enterprise scenario]. The goal is to maintain an enterprise view of the systems while still keeping the modeling local to each team.  In this example, we have two teams, one in Boston and one in Los Angeles, maintaining the systems. We'll maintain three workspaces:
1. a landscape workspace that models all the systems and their relations ships, maintained by the architecture team
1. a system workspace, maintained by each team, showing the details of each service and their relationships


== Prerequisites
* JDK 21 or greater

== Building
Structurizr is run as a container, eliminating the need to build anything but a few command can be run to verify the structure of the workspace files and launch the view.


* validate landscape
* validate Boston
* validate LA
* launch landscape
* launch Boston
* launch LA

== Installation

== Tips and Tricks

=== Architectural Diagrams
Run `docker run --pull always --interactive --tty --rm --name structurizr --publish 8080:8080 --env STRUCTURIZR_WORKSPACE_PATH=architectural-diagrams --volume $(pwd):/usr/local/structurizr structurizr/lite:latest` to launch the Structurizr application.

`docker run --pull always --interactive --tty --rm --name structurizr --publish 8080:8080 --env STRUCTURIZR_WORKSPACE_PATH=architectural-diagrams/bravo --volume $(pwd):/usr/local/structurizr structurizr/lite:latest`

== Troubleshooting

== Contributing

== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
* https://youtu.be/mqoU2C-USP0?si=dhz1tAGrC8cApXzC[The C4 Model – Misconceptions, Misuses & Mistakes]
* https://structurizr.com/[Structurizr]
* https://www.ilograph.com/[Ilograph]
